---

- name: Create user
  user:
    name: "{{ name }}"
    state: present
    groups: "{{ groups | default(omit) }}"
  sudo: yes

- name: SSH dir
  file:
    path: ~/.ssh
    state: directory
    owner: "{{ name }}"
    group: "{{ name }}"
    mode: "0700"
  sudo: yes
  sudo_user: "{{ name }}"

- name: Local git repos dir
  file:
    path: ~/git
    state: directory
    owner: "{{ name }}"
    group: "{{ name }}"
    mode: "0700"
  sudo: yes
  sudo_user: "{{ name }}"
   
- name: git-bash-prompt
  git:
    repo: git@github.com:magicmonty/bash-git-prompt.git
    dest: ~/git/bash-git-prompt
  sudo: yes
  sudo_user: "{{ name }}"
