---
- name: Me
  user: user="{{user_name}}" groups=admin
  sudo: yes

- name: Directory for local Git repos
  file: state=directory path={{git_dir}}
  sudo_user: "{{user_name}}"
  sudo: yes

- name: Bash Git Prompt
  git: repo=https://github.com/magicmonty/bash-git-prompt.git dest={{git_dir}}/bash-git-prompt
  sudo_user: "{{user_name}}"
  sudo: yes

- name: User SSH directory
  file: state=directory path={{home_dir}}/.ssh mode="0700"
  sudo_user: "{{user_name}}"
  sudo: yes

- name: Install agent-save for tmux
  copy: src=agent-save dest={{ssh_dir}}/agent-save  mode="0700"
  sudo_user: "{{user_name}}"
  sudo: yes

- name: Github Public key
  copy: dest={{ssh_public_key_file}} content="{{ssh_public_key}}" mode="0600"
  sudo_user: "{{user_name}}"
  sudo: yes

- name: Create .bash_profile if it doesn't exist 
  file: path={{item}} state=touch
  with_items:
    - "{{home_dir}}/.bash_profile"
    - "{{ssh_dir}}/config"
  sudo_user: "{{user_name}}"
  sudo: yes

- name: Do these things at login
  lineinfile: dest={{home_dir}}/.bash_profile line='{{item.line}}'
  with_items:
    - line: 'if ! [[ $TMUX ]] ; then tmux new-session -A -D -s $USER ; fi'
    - line: '$HOME/.ssh/agent-save'
    - line: 'source {{git_dir}}/bash-git-prompt/gitprompt.sh'
  sudo_user: "{{user_name}}"
  sudo: yes

- name: SSH Config settings for Github
  lineinfile: dest={{ssh_dir}}/config line='{{item.line}}' insertbefore="{{item.insertbefore | default(omit)}}" insertafter="{{item.insertafter | default(omit)}}"
  with_items:
    - line: 'Host *github.com'
      insertbefore: BOF
    - line: ' User git'
      insertafter: '^Host *github.com'
    - line: ' IdentityFile {{ssh_public_key_file}}'
      insertafter: '^ User git'


