export PATH=$HOME/bin:$PATH
export EDITOR=/usr/bin/vim

source $HOME/.ssh/agent-save

if ! [[ $TMUX ]] ; then
  tmux new-session -A -D -s $USER
fi

if [ -f $HOME/git/bash-git-prompt/gitprompt.sh ] ; then
  source $HOME/git/bash-git-prompt/gitprompt.sh
fi
